export const demoMedia = [
  {
    seedKey: 'demo-media-canteen-1',
    filename: 'demo-canteen-1.jpg',
    alt: '食堂档口外观',
    sourceUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=82',
  },
  {
    seedKey: 'demo-media-canteen-2',
    filename: 'demo-canteen-2.jpg',
    alt: '餐饮出餐区',
    sourceUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=82',
  },
  {
    seedKey: 'demo-media-street-1',
    filename: 'demo-street-1.jpg',
    alt: '校园商业街铺位',
    sourceUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1200&q=82',
  },
  {
    seedKey: 'demo-media-street-2',
    filename: 'demo-street-2.jpg',
    alt: '咖啡茶饮空间',
    sourceUrl: 'https://images.unsplash.com/photo-1498804103079-a6351b050096?auto=format&fit=crop&w=1200&q=82',
  },
  {
    seedKey: 'demo-media-retail-1',
    filename: 'demo-retail-1.jpg',
    alt: '校园零售铺位',
    sourceUrl: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&w=1200&q=82',
  },
  {
    seedKey: 'demo-media-retail-2',
    filename: 'demo-retail-2.jpg',
    alt: '便利零售货架',
    sourceUrl: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=1200&q=82',
  },
  {
    seedKey: 'demo-media-transfer-1',
    filename: 'demo-transfer-1.jpg',
    alt: '转让店铺门面',
    sourceUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1200&q=82',
  },
  {
    seedKey: 'demo-media-transfer-2',
    filename: 'demo-transfer-2.jpg',
    alt: '轻食店内部',
    sourceUrl: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=82',
  },
] as const

export const demoProjects = [
  {
    seedKey: 'demo-project-canteen-a05',
    mediaSeedKeys: ['demo-media-canteen-1', 'demo-media-canteen-2', 'demo-media-street-1'],
    opportunityType: 'leasing',
    title: '广州华商学院第一食堂二楼小吃档口',
    city: '广州',
    district: '增城',
    addressText: '广州华商学院荔湖校区第一食堂二楼 A05 档口',
    schoolName: '广州华商学院',
    schoolAlias: '华商学院',
    showFullSchoolName: true,
    projectType: '食堂档口',
    areaText: '15㎡',
    feeText: '3万元/年，另收 2% 管理费',
    suitableBusiness: ['粉面', '小吃', '水果'],
    unsuitableBusiness: ['重油烟', '奶茶'],
    highlights: ['学生人流集中', '免收转让费', '自带水电与排烟条件'],
    customerInfo: '覆盖约 1.2 万名在校师生，就餐高峰集中，适合高出餐效率品类。',
    cooperationMode: '纯租金模式，按年缴纳，押二付一。',
    viewingTimeText: '工作日 14:00-17:00，需提前一天预约。',
    advisorTips: '适合有校园出餐经验的轻餐饮团队，不建议做重油烟品类。',
    trafficTags: ['食堂二楼', '午晚餐高峰', '宿舍动线'],
    facilityTags: ['给排水', '排烟', '独立电表'],
    status: 'online',
    auditStatus: 'approved',
    isRecommended: true,
    sort: 100,
    remark: '黄金位置，优先推荐。',
  },
  {
    seedKey: 'demo-project-commercial-street',
    mediaSeedKeys: ['demo-media-street-1', 'demo-media-street-2', 'demo-media-canteen-2'],
    opportunityType: 'leasing',
    title: '华南师范大学石牌校区商业街茶饮店铺',
    city: '广州',
    district: '天河',
    addressText: '华南师范大学石牌校区西区商业街 2 号铺',
    schoolName: '华南师范大学',
    schoolAlias: '华师',
    showFullSchoolName: true,
    projectType: '校园商业街',
    areaText: '45㎡',
    feeText: '1.2万元/月，含物业费',
    suitableBusiness: ['奶茶', '咖啡', '面包烘焙'],
    unsuitableBusiness: ['重油烟', '粉面'],
    highlights: ['市中心成熟校区', '靠近女生宿舍区', '可办理餐饮许可'],
    customerInfo: '成熟校区商业街铺，适合品牌化茶饮、咖啡和轻烘焙。',
    cooperationMode: '固定租金，三年起签，无历史转让费。',
    viewingTimeText: '周一至周日均可预约看铺。',
    advisorTips: '需提前确认品牌形象、出品效率和校内准入条件。',
    trafficTags: ['商业街', '宿舍区入口', '高频复购'],
    facilityTags: ['上下水', '基础排烟', '门头展示'],
    status: 'online',
    auditStatus: 'approved',
    isRecommended: true,
    sort: 90,
    remark: '学校核心街铺，人流量大。',
  },
  {
    seedKey: 'demo-project-retail-west',
    mediaSeedKeys: ['demo-media-retail-1', 'demo-media-retail-2', 'demo-media-street-1'],
    opportunityType: 'leasing',
    title: '广东工业大学大学城校区西区超市旁铺位',
    city: '广州',
    district: '番禺',
    addressText: '广东工业大学大学城校区西区生活区 2 号楼底层',
    schoolName: '广东工业大学',
    schoolAlias: '广工',
    showFullSchoolName: false,
    projectType: '校内铺位',
    areaText: '30㎡',
    feeText: '8.5万元/年',
    suitableBusiness: ['便利店', '水果', '文具', '打印'],
    unsuitableBusiness: ['明火餐饮'],
    highlights: ['毗邻大型学生超市', '男生宿舍必经之路', '门头宽敞'],
    customerInfo: '大学城校区学生基数大，零售、文具、打印、零食需求稳定。',
    cooperationMode: '固定租金，押三付一，两年一签。',
    viewingTimeText: '提前半天预约，由招商经理带入校。',
    advisorTips: '适合低油烟、高复购服务型业态。',
    trafficTags: ['宿舍动线', '生活区', '超市旁'],
    facilityTags: ['独立电表', '门头位', '无燃气'],
    status: 'coming',
    auditStatus: 'approved',
    isRecommended: false,
    sort: 80,
    remark: '适合校园服务类项目。',
  },
  {
    seedKey: 'demo-project-transfer-light-food',
    mediaSeedKeys: ['demo-media-transfer-1', 'demo-media-transfer-2', 'demo-media-street-2'],
    opportunityType: 'transfer',
    title: '从化高校商业街轻食店委托转让',
    city: '广州',
    district: '从化',
    addressText: '从化区某高校商业街中段',
    schoolName: '从化某高校',
    schoolAlias: '从化高校',
    showFullSchoolName: false,
    projectType: '店铺转让',
    areaText: '50㎡',
    feeText: '转让费 6 万元，月租 7800 元',
    suitableBusiness: ['咖啡', '轻食', '烘焙', '小吃'],
    unsuitableBusiness: ['重油烟', '烧烤'],
    highlights: ['精装带设备', '剩余合同期 18 个月', '可协助和校方确认准入'],
    customerInfo: '原店有稳定学生社群客流，适合接手轻餐饮或烘焙类。',
    cooperationMode: '店主委托转让，平台协助约看与资料核验。',
    viewingTimeText: '需提前预约，避免影响原店经营。',
    advisorTips: '转让前必须确认原合同是否允许变更经营主体。',
    trafficTags: ['商业街中段', '社团活动区', '晚间客流'],
    facilityTags: ['含设备', '精装', '上下水'],
    transferInfo: {
      currentBusiness: '轻食简餐',
      monthlyRent: '7800 元/月',
      remainingTerm: '18 个月',
      includesEquipment: true,
      expectedTransferFee: '6 万元',
      contractTransferAllowed: '需校方确认',
    },
    status: 'full',
    auditStatus: 'approved',
    isRecommended: true,
    sort: 75,
    remark: '委托转让示例。',
  },
] as const

export const demoLeads = [
  {
    seedKey: 'demo-lead-zhang-canteen',
    projectSeedKey: 'demo-project-canteen-a05',
    submitterOpenId: 'dev-openid-local',
    leadType: 'leasing',
    sourceChannel: 'mini_program',
    name: '张老板',
    phone: '13800138000',
    businessType: '奶茶',
    budgetRange: '5-10万',
    regionPreference: '增城',
    hasCampusExperience: true,
    remark: '想尽快进场，希望确认 380V 动力电和排烟条件。',
    status: 'new',
    owner: '招商顾问小王',
  },
  {
    seedKey: 'demo-lead-li-transfer',
    projectSeedKey: 'demo-project-transfer-light-food',
    submitterOpenId: 'dev-openid-local',
    leadType: 'transfer',
    sourceChannel: 'mini_program',
    name: '李老板',
    phone: '13800138000',
    businessType: '轻食',
    budgetRange: '10-20万',
    regionPreference: '从化',
    hasCampusExperience: false,
    transferDetails: {
      locationText: '从化区某高校商业街中段',
      feeText: '50㎡，月租 7800 元',
      transferFee: '6 万元',
      remainingTerm: '18 个月',
      includesEquipment: true,
    },
    remark: '想接手带装修设备的店铺，先了解合同限制。',
    status: 'contacted',
    owner: '招商顾问小王',
  },
  {
    seedKey: 'demo-lead-equipment-sell',
    submitterOpenId: 'dev-openid-local',
    leadType: 'equipment_sell',
    sourceChannel: 'mini_program',
    name: '陈老板',
    phone: '13800138000',
    businessType: '双门冷藏柜',
    budgetRange: '2800元',
    regionPreference: '广州大学城',
    hasCampusExperience: false,
    equipmentDetails: {
      equipmentName: '双门冷藏柜',
      specText: '八成新，220V，可自提',
      equipmentCondition: '八成新',
      expectedPrice: '2800元',
    },
    remark: '设备八成新，可协助搬运。',
    status: 'interested',
    owner: '设备资源专员',
  },
  {
    seedKey: 'demo-lead-equipment-buy',
    submitterOpenId: 'dev-user-b',
    leadType: 'equipment_buy',
    sourceChannel: 'mini_program',
    name: '黄老板',
    phone: '13911112222',
    businessType: '制冰机',
    budgetRange: '5000元以内',
    regionPreference: '天河',
    hasCampusExperience: true,
    equipmentDetails: {
      equipmentName: '制冰机',
      specText: '适合 30 平茶饮店',
      equipmentCondition: '不限，功能正常优先',
      expectedPrice: '5000元以内',
    },
    remark: '需要适合茶饮店使用的制冰机。',
    status: 'new',
    owner: '设备资源专员',
  },
] as const

export const demoFollows = [
  {
    seedKey: 'demo-follow-li-transfer-1',
    leadSeedKey: 'demo-lead-li-transfer',
    content: '已电话沟通，客户接受转让费区间，下一步约店主提供合同摘要和设备清单。',
    operatorName: '招商顾问小王',
    nextFollowAtOffsetDays: 2,
  },
  {
    seedKey: 'demo-follow-li-transfer-2',
    leadSeedKey: 'demo-lead-li-transfer',
    content: '已补充发送店铺照片和租金说明，客户计划周末看铺。',
    operatorName: '招商顾问小王',
    nextFollowAtOffsetDays: 4,
  },
] as const
